### ISSUE TITLE
Lessons Learned document template creation

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#10]
### Description
We need to track thing that we did good or bad throughout the project implementation. But before that we need to create a document to log such information

### TODO
- [ ] Prepare a structured document for logging learned lessons

**Comment by Kirishanth-Manivannan** [comment]
https://docs.google.com/spreadsheets/d/1lasik0qBe7dox3AC4h3iMBK1vRtcywItTNJ1gwCT25Q/edit?usp=sharing

**Comment by RJSkudra** [comment]
Good job @Kirishanth-Manivannan ! Copy the spreadsheet over to the main project management Google Drive folder. And then close the issue as done.

**Comment by Kirishanth-Manivannan** [comment]
@RJSkudra  I do not have access to the root folder. Could you share me the link.

**Comment by RJSkudra** [comment]
@kitten-cake-png
