### ISSUE TITLE
Issue Register document template creation

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#11]
### Description
In prince2 we need to track issues regarding project

### TODO
- [ ] Propose a structured document for tracking and addressing project issues

**Comment by ahiyantra** [comment]
The template is now in the process of review.

[link to document](https://docs.google.com/spreadsheets/d/1Fy0nsvMcgxQTvtnqa_YsU5oiuuTEaMGwmznBocYv34U/edit?usp=sharing)

**Comment by ahiyantra** [comment]
The issue register document template is now in the process of getting updated after receiving feedback.
