### ISSUE TITLE
Quality Register document template creation

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#12]
### Description
To track whether we are achieving quality requirements, we need a structured document

### TODO
- [ ] Propose a structured document for tracking quality requirements

**Comment by Kirishanth-Manivannan** [comment]
Link to document :

https://docs.google.com/spreadsheets/d/1YuicI98uZWYa4wAg5Ep4j-v3WAD-M9TOswuH_YCBceA/edit?usp=sharing


Reviewers : 
Sandis Ābele (QA)
Anjitha Muraleedharan (QA Assistant)
Mohammed Muhaise (Project Assurance)
Kristīne Ivanova (Scrum Master)

Final approval by : 
Swarn Singh Warshaneyan (Senior User)
Satnam Singh (Senior Supplier)

**Comment by Kirishanth-Manivannan** [comment]
@dianabobriseva this template is stored in personal drive. can I store it in the root file put the task to done?
