### ISSUE TITLE
Software Design Description (SDD) document development

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#13]
### Description
After creation of SRS, we now can develop SDD document based on SRS (link_here) and project brief (link_here).

### TODO
- Create SDD document with following structure:
    - [ ] Introduction
        - Purpose
        - Scope
        - Audience
        - Definitions, acronyms, and abbreviations
        - Overview of the document structure
    - [ ] Overall Architecture
        - Description of the system architecture (e.g., layered, microservices, etc.)
        - Overview diagram illustrating the architecture
    - [ ] Design Considerations
        - Constraints
        - Dependencies
        - Risks and mitigations
        - System Components
        - Detailed description of each component/module
            - Purpose
            - Responsibilities
            - Interfaces
            - Interaction with other components
    - [ ] User Interface Design
        - Overview of the user interface
        - Wireframes or mockups
        - User experience considerations
    - [ ] System Interfaces
        - Interfaces with external systems (APIs, services)
        - Communication protocols
    - [ ] Security Design
        - Security considerations
        - Authentication and authorization mechanisms
    - [ ] Performance Considerations
        - Expected performance metrics
        - Scalability considerations
    - [ ] Testing and Validation
        - Overview of testing strategies
        - Validation procedures

**Comment by RJSkudra** [comment]
Is help still wanted or is there someone working on this document? Any progress on this? @Kirishanth-Manivannan

**Comment by Kirishanth-Manivannan** [comment]
https://docs.google.com/document/d/1bhZVK2E8sBsUWVC9PqwpggvfBQIy1RVQ5PQIhrFEKZc/edit?usp=share_link

help needed from @kitten-cake-png and @LBTU-IT-M24/development-team to complete the document.
