### ISSUE TITLE
Project Initiation Document development

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#21]
### Description
Since we have successfully completed development of Project Brief, it is time to create a Project Initiation Document (PID) before we can start a project (https://docs.google.com/document/d/1LocPARapfLourcAr0PUHYprFaU5h_YONL6g5CAO4sdk/edit?usp=sharing)

### TODO
- [ ]  Develop PID according to Project Brief

@LBTU-IT-M24/documentation-team

**Comment by kitten-cake-png** [comment]
[PID outline](https://docs.google.com/document/d/1A5SpjETNoMZ9jlYc5pY6fFKbApJhXH2v3x4SoeqrG6I/edit?usp=sharing)

**Comment by Kirishanth-Manivannan** [comment]
I have edited the risk management approach part in the pid document. update me if anything needs to be changed.
https://docs.google.com/document/d/1A5SpjETNoMZ9jlYc5pY6fFKbApJhXH2v3x4SoeqrG6I/edit?usp=sharing
