### ISSUE TITLE
7 principle & 7 pratices of PID

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#23]
[Link to register your descision](https://docs.google.com/document/d/1BxiQ63MQddihJRV4SmCg91Wqfco9gLuR89N2b3kXX7Y/edit)

**Comment by ahiyantra** [comment]
Excuse me but I already took one principle and one practice during the meeting ("Organizing" & "Define roles, responsibilities and relationships").

**Comment by RJSkudra** [comment]
This issue is meant for everyone. It's good that you have already chosen one principle & one practice.

**Comment by ahiyantra** [comment]
I mean that some other students were picking what I already picked earlier. I thought that I should point it out to avoid overlap.

**Comment by RJSkudra** [comment]
@ahiyantra wants to take all of these points?

**Comment by ahiyantra** [comment]
@RJSkudra, Yes.

**Comment by Kirishanth-Manivannan** [comment]
https://docs.google.com/document/d/1imK85UuC0A_6n5WB6KiwpH_tYwfhMP3-Iu-0BVtIq-s/edit?usp=sharing

**Comment by RJSkudra** [comment]
> https://docs.google.com/document/d/1imK85UuC0A_6n5WB6KiwpH_tYwfhMP3-Iu-0BVtIq-s/edit?usp=sharing

@Kirishanth-Manivannan What is this document supposed to be?



> [Link to register your descision](https://docs.google.com/document/d/1BxiQ63MQddihJRV4SmCg91Wqfco9gLuR89N2b3kXX7Y/edit)
> 
> [@LBTU-IT-M24](https://github.com/LBTU-IT-M24)

@AbhiSph @ahiyantra Please update this document with the updated names of who is responsible about which principle & practice.

**Comment by ahiyantra** [comment]
@RJSkudra, the empty document is where we're going to merge the 07 principles & 07 principles document's contents prepared by me & @AbhiSph combined. I'll be handling first 10 of 14 & he'll be handling last 04 of 14. I'm going to work on material for this document after finishing the issue register & issue report documents by updating them with feedback points from the review process. I don't know about when he's going to work on it.

**Comment by RJSkudra** [comment]
@ahiyantra Keep in mind, these principles and practices is more about vocally talking about them in the last lesson (26.10.2024) and not so much writing about them. @dianabobriseva or @kitten-cake-png or @andrejste7 can correct me if I am wrong. 
Also, again, please update this document with the up-to-date names: https://docs.google.com/document/d/1BxiQ63MQddihJRV4SmCg91Wqfco9gLuR89N2b3kXX7Y/edit?tab=t.0

**Comment by ahiyantra** [comment]
@RJSkudra, I've now updated the responsibility document that you linked. I'll now prepare according to what you pointed out, with the necessary spoken and written material.

**Comment by RJSkudra** [comment]
> https://docs.google.com/document/d/1imK85UuC0A_6n5WB6KiwpH_tYwfhMP3-Iu-0BVtIq-s/edit?usp=sharing

This document is empty, but in the time log @AbhiSph @ahiyantra  has written 6 hours of work?

**Comment by ahiyantra** [comment]
@RJSkudra, this document is a placeholder prepared in advance by someone else for copy-pasting the final work into. I & @AbhiSph are working in a different document. We're planning to copy-paste the draft version today evening into this document. I suggest waiting till then.
