### ISSUE TITLE
Risk Register document template creation

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#31]
### Description
We need a structured document that would allow us to address and manage risks that could possibly occur in ClassMate project

### TODO
- Create a Risk Management document template in _path_to_google_folder_
   - Should be an Excel file, that would allow to manage risks
   - Document must include information that required according to prince2 risk management standard

**Comment by Kirishanth-Manivannan** [comment]
https://docs.google.com/spreadsheets/d/1pJ8Pb7UptvLk0HNYweNOndyz7U5C_RmEWWkvVmWBdMY/edit?usp=sharing

@dianabobriseva the template is ready. please review it.

**Comment by RJSkudra** [comment]
What is the progress of this review? @dianabobriseva @Kirishanth-Manivannan Can we close this issue?
