### ISSUE TITLE
Initial widget is not centered.

### ISSUE THREAD

**Issue by SandisAbele** [LBTU-IT-M24/ClassMate#35]
![firefox_LLSwcwPPp7](https://github.com/user-attachments/assets/77e07647-5250-42b8-9800-3f5fbc397233)

I expect that the "Bookmarks" widget would show up in the center of the site.

**Comment by arturslast** [comment]
Can be re-tested @SandisAbele

**Comment by SandisAbele** [comment]
Re-tested:

![Ekrānuzņēmums 2024-10-05 163722](https://github.com/user-attachments/assets/69ee98cb-4ed2-4cf3-a9ba-17087f378018)

Bookmark widget defaults to the center of the screen.

FIXED

Closing the bug.
