### ISSUE TITLE
Multiple widgets are wrongly named

### ISSUE THREAD

**Issue by SandisAbele** [LBTU-IT-M24/ClassMate#36]
![9Ywal4lHpD](https://github.com/user-attachments/assets/611b3843-e422-4ad8-afbe-ee3471059d76)

So there are multiple widgets that are wrongly named "Clock" (Notes, Playlist, Lessons)

**Comment by arturslast** [comment]
@SandisAbele Can be re-tested

**Comment by SandisAbele** [comment]
Re-tested:

![Ekrānuzņēmums 2024-10-05 164636](https://github.com/user-attachments/assets/a234e48e-b8e4-4b43-b63b-41d70c2f3985)

Previously mentioned widgets are correctly named now.

FIXED

Can close the bug.
