### ISSUE TITLE
Software Requirement specification (SRS) document Development

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#4]
### Description
After gathering all needed information, we now can develop a very first version of SRS document based on project brief (link_here).

### TODO
- Create SRS document with following structure:
    - Introduction
        - Purpose
        - Scope
        - Definitions, acronyms, and abbreviations
    - Overall Description
        - Product perspective
        - Product functions
        - Operating environment
        - Design and implementation constraints
    - Specific Requirements
        - Functional requirements (detailed description of features)
        - Non-functional requirements (performance, security, usability, etc.)
        - Interface requirements (user interfaces, APIs, etc.)
        - System requirements (hardware and software)
    - Use Cases
        - Description of user interactions with the system
    - System Features
        - Detailed description of each feature and its requirements
    - Performance Requirements
        - Speed, response time, availability, etc.
        - Security Requirements
        - Security measures and protocols
    - Quality Attributes
        - Maintainability, portability, scalability, etc.
    - Criteria for acceptance of the software

**Comment by Kirishanth-Manivannan** [comment]
https://docs.google.com/document/d/1r6-axNTcfPYe9_gQVH4CrO8xSns0DwNA/edit?usp=sharing&ouid=109983845275616998138&rtpof=true&sd=true

@kitten-cake-png , @dianabobriseva could you please review this document.

**Comment by dianabobriseva** [comment]
@Kirishanth-Manivannan reviewed. Please check comments

**Comment by Kirishanth-Manivannan** [comment]
Adding use cases to the SRS
