### ISSUE TITLE
Project Issue report

### ISSUE THREAD

**Issue by dianabobriseva** [LBTU-IT-M24/ClassMate#49]
### Description
Since project started, issues should be documented.

### TODO:
- [ ] Register project issues

**Comment by ahiyantra** [comment]
The template is now in the process of review.

[link to document](https://docs.google.com/spreadsheets/d/1Li6ynl6RW2vmvRfL3R3phsANDHW7h2wGiRhrWNIjbto/edit?usp=sharing)

**Comment by ahiyantra** [comment]
@RJSkudra, as far as i can understand, the issue register & issue report documents are separate from the risk register document but maybe @Kirishanth-Manivannan can clarify things better for us.

**Comment by ahiyantra** [comment]
The issue report template is now in the process of getting updated after receiving feedback.
