### ISSUE TITLE
Scrum presentation preparation

### ISSUE THREAD

**Issue by andrejste7** [LBTU-IT-M24/ClassMate#58]
### Description
Since we are running scrum development team, will need to make a brief descriptive presentation regarding the process

### TODO
- [x] Create a presentation covering following points (Also refer 14. slide of professor's presentation):
  - Backlogs (how it looks like and why it is used)
  - Scrum process itself (sprints, etc.)
  - Use of Kanban (how we deal with tasks)

**Comment by KristineIvanova** [comment]
Presentation created and presented.
