### ISSUE TITLE
Risk analysis matrix creation for PID

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#6]
### Description
Before starting development stage, we need a defined set of expected risks that might occur in following stage

### TODO
- [x] Create a risk analysis matrix for PID

**Comment by Kirishanth-Manivannan** [comment]
initial matrix has been added to PID on 08/10/2024

**Comment by andrejste7** [comment]
could you also provide a link to the exact document and a place where is it?

**Comment by Kirishanth-Manivannan** [comment]
![Image](https://github.com/user-attachments/assets/d49464b6-e6af-48dc-b632-419d0d010a4b)

https://docs.google.com/document/d/1A5SpjETNoMZ9jlYc5pY6fFKbApJhXH2v3x4SoeqrG6I/edit?tab=t.0

the updated version based on risk register report will be uploaded before 24/10/2024

**Comment by andrejste7** [comment]
oke, all good. Just the task is still in progress. Will close it then
