### ISSUE TITLE
New design implementation

### ISSUE THREAD

**Issue by andrejste7** [LBTU-IT-M24/ClassMate#67]
### Description
After the UI mockup (https://github.com/orgs/LBTU-IT-M24/projects/3/views/1?layout=board&pane=issue&itemId=81367608) will be done and ready to be implemented, we need to implement it

### TODO
- Implement design according to UI mockup

**Comment by andrejste7** [comment]
https://xd.adobe.com/view/92deba9e-b0e7-4df6-8705-71db4bc6c7d1-c78d/screen/2546c902-c422-4198-96d0-80b5a6d9fda8/

**Comment by RJSkudra** [comment]
@SandisAbele Probably needs to test this?

**Comment by SandisAbele** [comment]
Tested/Inspected:

Design looks consistent across student/teacher sections, the widgets also are consistent with the color scheme, brainstorm board as well. 

QA Pass.
