### ISSUE TITLE
Project risks registration in Risk Management (Risk Register) document

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#7]
### Description
Due project development project risks should be registered

### TODO
- [ ] Write project risks in risk register

**Comment by Kirishanth-Manivannan** [comment]
https://docs.google.com/spreadsheets/d/1pJ8Pb7UptvLk0HNYweNOndyz7U5C_RmEWWkvVmWBdMY/edit?usp=sharing

https://docs.google.com/document/d/1vQl0BDbR9gpDnurKpo97gFh8y3YLA3Z8t2w2R15iPc0/edit?usp=sharing
