### ISSUE TITLE
Implement bookmark add/delete logic

### ISSUE THREAD

**Issue by andrejste7** [LBTU-IT-M24/ClassMate#73]
### Description
We have added bookmark component, but we do not have an option to add or delete bookmarks

### TODO
- [x] Add logic for adding and deleting bookmarks from bookmark widget

**Comment by arturslast** [comment]
can be tested @SandisAbele

**Comment by SandisAbele** [comment]
Tested:

Bookmarks can be added/removed, link redirecting works. 

QA Pass.
