### ISSUE TITLE
Existing widgets adjustment to use NaiveUI

### ISSUE THREAD

**Issue by andrejste7** [LBTU-IT-M24/ClassMate#75]
### Description
After switching from bootstrap to naive, we now have broken widget design

### TODO
- [x] Make needed adjustments for widgets to work with naive, not bootstrap

**Comment by arturslast** [comment]
can be tested @SandisAbele

**Comment by SandisAbele** [comment]
Tested

Widgets are no longer broken :D

QA Pass.
