### ISSUE TITLE
Adding sign-out button

### ISSUE THREAD

**Issue by andrejste7** [LBTU-IT-M24/ClassMate#76]
### Description
We have implemented authorization mechanism, but we have no button to sign out currently

### TODO
- [x] Fix this mistake by adding an option to sign out in drawer view

**Comment by arturslast** [comment]
can be tested @SandisAbele

**Comment by SandisAbele** [comment]
Tested:

Logout functionality works as expected, takes you back to the main screen.

QA Pass, ticket can be closed.
