### ISSUE TITLE
Widget configuration option disabling for students

### ISSUE THREAD

**Issue by andrejste7** [LBTU-IT-M24/ClassMate#77]
### Description
With having option to separate students from teachers, now we need to implement actual restrictions

### TODO
- [x] Restrict students from modifying widget settings

**Comment by arturslast** [comment]
can be tested @SandisAbele

**Comment by SandisAbele** [comment]
Tested

The feature listed above is implemented - Teachers can modify their widgets, students can not.

QA Pass
