### ISSUE TITLE
Default theme according to system defaults

### ISSUE THREAD

**Issue by andrejste7** [LBTU-IT-M24/ClassMate#83]
### Description
Now we have dark and light mode, but it is not synced to system defaults

### TODO
- [x] Sync default theme to system defaults

**Comment by arturslast** [comment]
https://github.com/LBTU-IT-M24/ClassMate/commit/76e7c68a37effd7d9a3a5f405bd6ef80d2ea68ed matched default web theme to system settings. @andrejste7

**Comment by arturslast** [comment]
can be tested (make sure cache is clear for style configuration) @SandisAbele

**Comment by SandisAbele** [comment]
Tested:

Works with system default, can also change it manually.

QA Pass
